# Generated by Django 2.0 on 2018-03-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=10)),
                ('quote', models.CharField(max_length=10)),
                ('bid', models.FloatField(default=None, null=True)),
                ('ask', models.FloatField(default=None, null=True)),
                ('last', models.FloatField(default=None, null=True)),
                ('base_volume', models.FloatField(default=None, null=True)),
                ('quote_volume', models.FloatField(default=None, null=True)),
                ('last_updated', models.DateTimeField(default=None, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.CryptoExchange')),
            ],
        ),
    ]
