# Generated by Django 2.0 on 2018-03-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
