import sys
sys.path.insert(0, "/Users/rileystephens/Documents/Projects/FAM/")
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'FAM.settings'
from django.conf import settings
import django
django.setup()
from sources.models import StockExchange, CryptoExchange


""" Add all stock exchanges to StockExchange Database """
def add_stockExchange(name, code):
    exchange = StockExchange()
    exchange.name = name
    exchange.code = code
    exchange.save()

stock_exchanges = StockExchange.objects.all()
exchanges = list((item.name for item in stock_exchanges))

if "NYSE MKT" not in exchanges:
    add_stockExchange("NYSE MKT","A")

if "NASDAQ OMX BX" not in exchanges:
    add_stockExchange("NASDAQ OMX BX","B")

if "National Stock Exchange" not in exchanges:
    add_stockExchange("National Stock Exchange","C")

if "FINRA ADF" not in exchanges:
    add_stockExchange("FINRA ADF","D")

if "Market Independent (Generated by Nasdaq SIP)" not in exchanges:
    add_stockExchange("Market Independent (Generated by Nasdaq SIP)", "E")

if "Mutual Funds/Money Markets (NASDAQ)" not in exchanges:
    add_stockExchange("Mutual Funds/Money Markets (NASDAQ)","F")

if "International Securities Exchange" not in exchanges:
    add_stockExchange("International Securities Exchange","I")

if "Direct Edge A" not in exchanges:
    add_stockExchange("Direct Edge A","J")

if "Direct Edge X" not in exchanges:
    add_stockExchange("Direct Edge X","K")

if "Chicago Stock Exchange" not in exchanges:
    add_stockExchange("Chicago Stock Exchange","M")

if "NYSE" not in exchanges:
    add_stockExchange("NYSE","N")

if "NYSE Arca" not in exchanges:
    add_stockExchange("NYSE Arca","P")

if "NASDAQ OMX" not in exchanges:
    add_stockExchange("NASDAQ OMX","Q")

if "NASDAQ Small Cap" not in exchanges:
    add_stockExchange("NASDAQ Small Cap","S")

if "NASDAQ Int" not in exchanges:
    add_stockExchange("NASDAQ Int","T")

if "OTCBB" not in exchanges:
    add_stockExchange("OTCBB","U")

if "OTC other" not in exchanges:
    add_stockExchange("OTC other","V")

if "CBOE" not in exchanges:
    add_stockExchange("CBOE","W")

if "NASDAQ OMX PSX" not in exchanges:
    add_stockExchange("NASDAQ OMX PSX","X")

if "GLOBEX" not in exchanges:
    add_stockExchange("GLOBEX","G")

if "BATS Y-Exchange" not in exchanges:
    add_stockExchange("BATS Y-Exchange","Y")

if "BATS" not in exchanges:
    add_stockExchange("BATS","Z")


""" Add all cryptocurrency exchanges to CryptoExchange Database """
def add_cryptoExchange(name):
    exchange = CryptoExchange()
    exchange.name = name
    exchange.save()

crypto_exchanges = CryptoExchange.objects.all()
exchanges = list((item.name for item in crypto_exchanges))

if "HitBTC" not in exchanges:
    add_cryptoExchange("HitBTC")

if "Coinbase" not in exchanges:
    add_cryptoExchange("Coinbase")

if "Gemini" not in exchanges:
    add_cryptoExchange("Gemini")

if "Poloniex" not in exchanges:
    add_cryptoExchange("Poloniex")
