# Generated by Django 2.0 on 2018-03-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500, null=True)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.FloatField(default=None)),
                ('bid', models.FloatField(default=None)),
                ('ask', models.FloatField(default=None)),
                ('last', models.FloatField(default=None)),
                ('volume', models.FloatField(default=None, null=True)),
                ('high', models.FloatField(default=None, null=True)),
                ('low', models.FloatField(default=None, null=True)),
                ('open_price', models.FloatField(default=None, null=True)),
                ('close_price', models.FloatField(default=None, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.StockExchange')),
            ],
        ),
    ]
